### ISSUE TITLE
Runtime error: cannot read "NDSKEYS" in spacecraft file   

### ISSUE THREAD

**Issue by siddcodes11** [ranieremenezes/easyFermi#3]
Hey there , while working on easyFermi I am getting error , " RuntimeError: Cannot read keyword "NDSKEYS" in file "/home/siddhant/Desktop/easyFermiandromeda/srcmap_00.fits" (CFITSIO ERROR 202: keyword not found in header)
Aborted (core dumped) "   . I have tried with different source objects (example given in youtube tutorial as well as Coma galaxy cluster, andromeda and Vela Pulsar ) & using latest version yet the problem persists. Can you please recommend how shall I proceed to solve the issue. 
[fermipy.log](https://github.com/ranieremenezes/easyFermi/files/10342510/fermipy.log)
[list.txt](https://github.com/ranieremenezes/easyFermi/files/10342521/list.txt)
[evfile_00.txt](https://github.com/ranieremenezes/easyFermi/files/10342522/evfile_00.txt)
/home/siddhant/Desktop/easyFermiandromeda/config.yaml

I have herein attached the necessary files for andromeda galaxy 

Thanks & Regards

Siddhant Manna
Research Scholar
IIT Hyderabad

**Comment by ranieremenezes** [comment]
Dear @siddcodes11 , 

Thank you for contacting me. 

From the fermipy.log file, seems like your problem is with the Galactic model gll_iem_v07.fits file. I will ask you to download it again from this webpage: https://fermi.gsfc.nasa.gov/ssc/data/access/lat/BackgroundModels.html . My guess is that your file is corrupted. It should have 464.8 MB.

Let me know if the error persists after that. 

Best,
Raniere

**Comment by siddcodes11** [comment]
Thank you for your reply. I will do it & let you know if the
problem persists.

Thanks & Regards

**Comment by siddcodes11** [comment]
Hey there , thanks for getting back to me so quickly. I tried downloading
the data from given website & perform the analysis but it showed the same
error as before.

Can you please suggest me what else options can I try ?

I would be highly obliged to you.

Thanks & Regards.

**Comment by ranieremenezes** [comment]
Hi @siddcodes11 ,

Ok, so the Galactic model file is not corrupted. I have some other suggestions:

1) Please install the latest version of fermipy with the following command (in the fermi encironment):
_pip install fermipy==1.2_
I noticed that you are using version 1.1.6 

2) Check if the photon files are in the same energy and time range that you are entering in easyFermi. I noticed that your analysis is from 100 MeV up to 300000 MeV and from tmin=239557417 to tmax=271036801. For a first analysis, I always recommend starting from 1000 MeV instead of 100 MeV. All the process will be much faster and the chance of going out of RAM is very low.

3) Make sure you deleted the files generated by easyFermi before running a new analysis.

4) In the title of this issue you mentioned that the problem is in the spacecraft file, but seems like it is in the source map file srcmap_00.fits. Do you confirm that you also have a problem with the spacecraft file? From what I saw in the fermipy.log file, the spacecraft file seems ok. 

If this doesn't work, I will ask you to send me the config.yaml file generated by easyFermi in the output directory, the new fermipy.log file, and a copy of the output printed in your terminal.

Best,

**Comment by siddcodes11** [comment]
Thank you so much for your kind help.  I am really obliged to you. I would
check all the steps as you told & will let you know if it worked. Yes, you
are right the problem is with the source code file & not spacecraft file.

Thanks & Best Regards
Siddhant

**Comment by siddcodes11** [comment]
Respected  Sir/Ma'am ,

Thank you so much for your recommendations. I did as you suggested & for
the galactic object mentioned in easyFermi installation paper , I got
successful result. The program ran successfully & all the graphs were
generated.
But, unfortunately when I am trying the same for coma cluster I am
receiving an error message :
*" ValueError: zero-size array to reduction operation maximum which has no
identity " *

I tried multiple times but received the same error. Can you kindly please
suggest me how to proceed. I would be highly obliged to you.

Thanks & Regards

Siddhant
IIT Hyderabad

**Comment by siddcodes11** [comment]
Hey, updating the easyFermi software solved the problem. Thank you so much
for your kind help.

Thanks & Regards
Siddhant
Research Scholar
IIT Hyderabad

**Comment by ranieremenezes** [comment]
Hi @siddcodes11 ,

I am glad to know that everything is working.

Best,

**Comment by siddcodes11** [comment]
Respected sir , while doing the analysis using easyFermi , I am able to
generate counts v/s Energy graph but in recent literature they have plotted
E^2 dN/dE v/s Energy Graphs.

Can you please suggest me how can I convert the graph.

I would be highly obliged to you

Thanks & Regards

Siddhant Manna
Research Scholar
Astrophysics ,
IIT Hyderabad
