### ISSUE TITLE
SED curve different than existing literature for coma cluster

### ISSUE THREAD

**Issue by siddcodes11** [ranieremenezes/easyfermi#6]
Hey, I am trying to do Fermi-LAT analysis for coma cluster & I got the SED curve which I have attached below. I used coordinates 194.95,27.98 & search radius 12 degree. I referred to XI, WANG, LIANG, PENG, YANG, and LIU PHYS. REV. D 98, 063006 (2018)
for reference and they have used the same coordinates , search radius and energy range 200 MeV - 300 GeV but got a different SED curve and similar for Vardan Baghmanyan et al . In their analysis they have used fermitools. I have attached the SED curves below, can you please let me know why are they not same ?
![Screenshot from 2023-02-09 13-46-25](https://user-images.githubusercontent.com/116638734/218308049-f871d2af-e621-4668-841d-91c77fce042a.png)
![Screenshot from 2023-02-08 22-20-42](https://user-images.githubusercontent.com/116638734/218308065-c5875351-2978-4455-a5ba-d4d0f58dcdc3.png)
![Screenshot from 2023-02-12 16-53-58](https://user-images.githubusercontent.com/116638734/218308122-104c5b90-569b-44ae-b088-9d4bada55ba3.png)

**Comment by ranieremenezes** [comment]
Hi @siddcodes11 , please note that you are working with different coordinates in comparison with the gamma-ray source found in Baghmanyan et al. 2021 and Xi et al. 2018. The position of the gamma-ray source that they find is RA = 194.148° and Dec = 27.683°, corresponding to the source "4FGL J1256.9+2736" in the 4FGL catalog.

To repeat their analysis you will have to use the same coordinates I listed above, however, note that they are dealing with an **extended** gamma-ray source and, as stated in the easyFermi paper (https://www.sciencedirect.com/science/article/pii/S2213133722000403) and YouTube tutorials  (link here: https://www.youtube.com/channel/UCeLCfEoWasUKky6CPNN_opQ), easyFermi is recommended for **point-like** sources. In any case, you may achieve a similar result to them, but not the same.

**Comment by siddcodes11** [comment]
Thank you so much ..I will try and let you know

**Comment by siddcodes11** [comment]
Can you please let me know how to proceed for extended sources , is there a
way to do analysis using easyFermi

**Comment by ranieremenezes** [comment]
Hi @siddcodes11,

Yes, there is a way, but it is not straight forward as the point-source analysis with easyFermi.

In summary, you will have to create an extended template by yourself following the tutorial here: https://fermi.gsfc.nasa.gov/ssc/data/analysis/scitools/extended/extended.html, and then add it manually to the config.yaml file (which is generated automatically with easyFermi), for instance, if you name your template "template.fits", you have to change the following region of the config file:

model:
  src_roiwidth : 20.0
  galdiff  : 'path/to/background/gll_iem_v07.fits'
  isodiff  : '/path/to/background/iso_P8R3_SOURCE_V3_v1.txt'
  catalogs : ['4FGL-DR3']
  **sources :
    - { name: 'SourceName', glon : 120.0, glat : 0.0,
     SpectrumType : 'PowerLaw', Index : 2.0, Scale : 1000, Prefactor : !!float 1e-11,
     SpatialModel: 'SpatialMap', Spatial_Filename : 'template.fits' }**

Note that the "Extension" option given by easyFermi is recommended only if your target presents gamma-ray emission in the center of the RoI and if it can be approximated by a disk or 2D Gaussian shape. For instance, you can use it to compute the extension of some supernova remnants. Since your case with the Coma Cluster is more complicated than that, I would recommend the extended analysis done in the tutorial above. Note also that using fermipy will give you more possibilities than using easyFermi. Maybe fermipy will be more suited to your analysis than easyFermi.

**Comment by siddcodes11** [comment]
Thank you for your response , I will try to do as you suggested and will
let you know if I face any problem.
