### ISSUE TITLE
Encountered a ‘Too many open files’ error while processing the light curve

### ISSUE THREAD

**Issue by haruku99** [ranieremenezes/easyfermi#62]
Hello, I encountered a ‘Too many open files’ error while processing the light curve.

I was using easyfermi on my Mac to analyze the light curve of OT 081 over a span of 14 years, and I encountered an error: ‘Too many open files’. I have attached the fermipy.log, config.yaml, information in the easyfermi window, and a screenshot of some terminal information (all in a zip file) below. Could you please tell me how to solve this problem? By the way, is there a way to continue the analysis from where it was interrupted before (for example, continue from bin75)? Because this really takes a lot of time.  If you could tell me how to do, I would be very grateful.
[package.zip](https://github.com/ranieremenezes/easyfermi/files/15127186/package.zip)

**Comment by ranieremenezes** [comment]
Hi @haruku99 ,

Did you tried running easyfermi in other configurations? E.g. 2 years of data instead of 14 and less time bins for the light curve (lets say 50)?

**I encountered an error: ‘Too many open files’**
- Try using fewer bins for the light curve.

**By the way, is there a way to continue the analysis from where it was interrupted before (for example, continue from bin75)?**
- The general analysis yes, so you don't need to recompute the main ltcube, which is the longest step (~10h~14h for 14 years of data). For the light curve, it will rerun everything, so it will take some time.

**Because this really takes a lot of time.**
- At the moment, fermipy does not allow multithreading for macOC. There is an open issue for that here: https://github.com/fermiPy/fermipy/issues/565. If the next release of fermipy allows for it, we will do the same in easyfermi. At the moment, the fastest way is using a Linux, where the multithreading is allowed.

The best way for you to proceed at this moment is by slicing the time window. E.g., open easyfermi in 4 terminals and use time intervals from 2008 to 2012, 2012 to 2016 and so on. You can also play with the time bins.

**Comment by haruku99** [comment]
Thank you for your reply. Indeed, I have attempted to analyze the light curve of BL Lac (lasting nearly four and a half years, with 20 bins, corresponding to the "Light curves" section in the easyfermi tutorial), and I was able to reproduce the same results as in the tutorial.

Next, I will try to compress the time range, for example, dividing a 14-year time window into three shorter ones (e.g., each with 33 bins). I sincerely appreciate your advice, and if I encounter any problems, I will tell you.
